\ Rebel Forth Sprite Bank: rebel-rogue
\ Generated by Rebel Sprite Editor
\ Tag: SPRT, Entry Count: 16

HEX

\ 16-Color Palette (0xRRGGBB)
CREATE REBEL-ROGUE-PALETTE
  1A1C2C ,  \ [0] #1a1c2c
  5D275D ,  \ [1] #5d275d
  B13E53 ,  \ [2] #b13e53
  EF7D57 ,  \ [3] #ef7d57
  FFCD75 ,  \ [4] #ffcd75
  A7F070 ,  \ [5] #a7f070
  38B764 ,  \ [6] #38b764
  257179 ,  \ [7] #257179
  29366F ,  \ [8] #29366f
  3B5DC9 ,  \ [9] #3b5dc9
  41A6F6 ,  \ [10] #41a6f6
  73EFF7 ,  \ [11] #73eff7
  F4F4F4 ,  \ [12] #f4f4f4
  94B0C2 ,  \ [13] #94b0c2
  566C86 ,  \ [14] #566c86
  333C57 ,  \ [15] #333c57

\ Sprite Metadata Table: width height flags reserved
CREATE REBEL-ROGUE-ENTRIES
  10 C, 10 C, 0 C, 0 C,  \ #0 hero_idle_0
  10 C, 10 C, 0 C, 0 C,  \ #1 hero_idle_1
  10 C, 10 C, 0 C, 0 C,  \ #2 hero_walk_0
  10 C, 10 C, 0 C, 0 C,  \ #3 hero_walk_1
  10 C, 10 C, 0 C, 0 C,  \ #4 monster_goblin
  10 C, 10 C, 0 C, 0 C,  \ #5 monster_skeleton
  10 C, 10 C, 0 C, 0 C,  \ #6 boss_dragon
  10 C, 10 C, 0 C, 0 C,  \ #7 item_sword
  10 C, 10 C, 0 C, 0 C,  \ #8 item_shield
  8 C, 8 C, 0 C, 0 C,  \ #9 item_potion
  8 C, 8 C, 0 C, 0 C,  \ #10 item_coin
  8 C, 8 C, 0 C, 0 C,  \ #11 item_key
  8 C, 8 C, 0 C, 0 C,  \ #12 tile_wall
  8 C, 8 C, 0 C, 0 C,  \ #13 tile_floor
  8 C, 8 C, 0 C, 0 C,  \ #14 tile_door_closed
  8 C, 8 C, 0 C, 0 C,  \ #15 tile_chest

DECIMAL
