/**
 * Rebel Sprite Bank: rebel_rogue
 * Generated by Rebel Sprite Editor
 *
 * Format: 4bpp, 16-entry 0xRRGGBB Palette, Contiguous 4bpp Pixel Data.
 * Entry Count: 16 sprite(s) / tile(s)
 */

export const REBEL_ROGUE_NAME = 'rebel_rogue';
export const REBEL_ROGUE_ENTRY_COUNT = 16;

// 16-Entry 0xRRGGBB Color Palette (Index 0 is Transparent / Color-Key)
export const REBEL_ROGUE_PALETTE: readonly number[] = [
  0x1A1C2C, // [ 0] #1a1c2c (Transparent)
  0x5D275D, // [ 1] #5d275d 
  0xB13E53, // [ 2] #b13e53 
  0xEF7D57, // [ 3] #ef7d57 
  0xFFCD75, // [ 4] #ffcd75 
  0xA7F070, // [ 5] #a7f070 
  0x38B764, // [ 6] #38b764 
  0x257179, // [ 7] #257179 
  0x29366F, // [ 8] #29366f 
  0x3B5DC9, // [ 9] #3b5dc9 
  0x41A6F6, // [10] #41a6f6 
  0x73EFF7, // [11] #73eff7 
  0xF4F4F4, // [12] #f4f4f4 
  0x94B0C2, // [13] #94b0c2 
  0x566C86, // [14] #566c86 
  0x333C57, // [15] #333c57 
];

export interface SpriteEntryMetadata {
  id: number;
  name: string;
  width: number;
  height: number;
  hFlip: boolean;
  vFlip: boolean;
  offset: number;
  byteLength: number;
}

export const REBEL_ROGUE_ENTRIES: readonly SpriteEntryMetadata[] = [
  { id: 0, name: 'hero_idle_0', width: 16, height: 16, hFlip: false, vFlip: false, offset: 128, byteLength: 128 },
  { id: 1, name: 'hero_idle_1', width: 16, height: 16, hFlip: false, vFlip: false, offset: 256, byteLength: 128 },
  { id: 2, name: 'hero_walk_0', width: 16, height: 16, hFlip: false, vFlip: false, offset: 384, byteLength: 128 },
  { id: 3, name: 'hero_walk_1', width: 16, height: 16, hFlip: false, vFlip: false, offset: 512, byteLength: 128 },
  { id: 4, name: 'monster_goblin', width: 16, height: 16, hFlip: false, vFlip: false, offset: 640, byteLength: 128 },
  { id: 5, name: 'monster_skeleton', width: 16, height: 16, hFlip: false, vFlip: false, offset: 768, byteLength: 128 },
  { id: 6, name: 'boss_dragon', width: 16, height: 16, hFlip: false, vFlip: false, offset: 896, byteLength: 128 },
  { id: 7, name: 'item_sword', width: 16, height: 16, hFlip: false, vFlip: false, offset: 1024, byteLength: 128 },
  { id: 8, name: 'item_shield', width: 16, height: 16, hFlip: false, vFlip: false, offset: 1152, byteLength: 128 },
  { id: 9, name: 'item_potion', width: 8, height: 8, hFlip: false, vFlip: false, offset: 1280, byteLength: 32 },
  { id: 10, name: 'item_coin', width: 8, height: 8, hFlip: false, vFlip: false, offset: 1312, byteLength: 32 },
  { id: 11, name: 'item_key', width: 8, height: 8, hFlip: false, vFlip: false, offset: 1344, byteLength: 32 },
  { id: 12, name: 'tile_wall', width: 8, height: 8, hFlip: false, vFlip: false, offset: 1376, byteLength: 32 },
  { id: 13, name: 'tile_floor', width: 8, height: 8, hFlip: false, vFlip: false, offset: 1408, byteLength: 32 },
  { id: 14, name: 'tile_door_closed', width: 8, height: 8, hFlip: false, vFlip: false, offset: 1440, byteLength: 32 },
  { id: 15, name: 'tile_chest', width: 8, height: 8, hFlip: false, vFlip: false, offset: 1472, byteLength: 32 },
];

// prettier-ignore
export const REBEL_ROGUE_PIXEL_DATA = new Uint8Array([
  // Sprite #0: hero_idle_0 (16x16 px, 128 bytes)
  0x00, 0x00, 0x00, 0x44, 0x44, 0x00, 0x00, 0x00, // row 0
  0x00, 0x00, 0x04, 0x44, 0x44, 0x40, 0x00, 0x00, // row 1
  0x00, 0x00, 0x44, 0x44, 0x44, 0x44, 0x00, 0x00, // row 2
  0x00, 0x00, 0x4F, 0xFF, 0xFF, 0x44, 0x00, 0x00, // row 3
  0x00, 0x00, 0x4F, 0x1F, 0xF1, 0xF4, 0x00, 0x00, // row 4
  0x00, 0x00, 0x4F, 0xFF, 0xFF, 0xF4, 0x00, 0x00, // row 5
  0x00, 0x00, 0x04, 0xF4, 0x4F, 0x40, 0x00, 0x00, // row 6
  0x00, 0x00, 0x00, 0x44, 0x44, 0x00, 0x00, 0x00, // row 7
  0x00, 0x00, 0x08, 0x88, 0x88, 0x80, 0x00, 0x00, // row 8
  0x00, 0x00, 0x88, 0x99, 0x99, 0x88, 0x00, 0x00, // row 9
  0x00, 0x08, 0x88, 0x99, 0x99, 0x88, 0x80, 0x00, // row 10
  0x00, 0x00, 0x88, 0x88, 0x88, 0x88, 0x00, 0x00, // row 11
  0x00, 0x00, 0x08, 0x00, 0x00, 0x80, 0x00, 0x00, // row 12
  0x00, 0x00, 0x08, 0x00, 0x00, 0x80, 0x00, 0x00, // row 13
  0x00, 0x00, 0x0E, 0x00, 0x00, 0xE0, 0x00, 0x00, // row 14
  0x00, 0x00, 0xEE, 0x00, 0x00, 0xEE, 0x00, 0x00, // row 15
]);

/** Reads a 4bpp pixel (0..15) for a given sprite entry */
export function getRebelRoguePixel(entryId: number, x: number, y: number): number {
  const entry = REBEL_ROGUE_ENTRIES[entryId];
  if (!entry || x < 0 || x >= entry.width || y < 0 || y >= entry.height) return 0;
  const start = entry.offset - (64 + REBEL_ROGUE_ENTRY_COUNT * 4);
  const byteIdx = start + y * (entry.width / 2) + (x >> 1);
  const byteVal = REBEL_ROGUE_PIXEL_DATA[byteIdx];
  return (x % 2 === 0) ? ((byteVal >> 4) & 0x0F) : (byteVal & 0x0F);
}
